# Generated by Django 4.0.3 on 2022-05-19 11:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 15, 41, 59, 949675)),
        ),
        migrations.AddField(
            model_name='productview',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 15, 41, 59, 949675)),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
