# Generated by Django 4.0.5 on 2022-07-14 11:58

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_image_alter_product_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=product.models.product_image_path),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
