# Generated by Django 4.0.6 on 2022-07-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_category_level_remove_category_lft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
