# Generated by Django 4.0.3 on 2022-05-19 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 15, 41, 59, 949675)),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 15, 41, 59, 949675)),
        ),
    ]
