# Generated by Django 4.0.3 on 2022-05-18 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_discount_price'),
        ('user', '0003_address_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pros', models.CharField(default='', max_length=100)),
                ('cons', models.CharField(default='', max_length=100)),
                ('content', models.CharField(default='', max_length=100)),
                ('value', models.CharField(choices=[('u', 'Up Value'), ('d', 'Down Value'), ('o', 'Not Sure')], max_length=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_product', to='product.product')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
