# Generated by Django 4.0.3 on 2022-05-19 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 15, 41, 59, 949675)),
        ),
        migrations.AddField(
            model_name='review',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
