# Generated by Django 4.0.6 on 2022-07-26 15:32

import datetime
from django.db import migrations, models
import user.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_review_created_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRequest',
            fields=[
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='phone', max_length=7)),
                ('pass_code', models.CharField(default='', max_length=5)),
                ('expire_time', models.DateTimeField(default=datetime.datetime(2022, 7, 26, 20, 4, 50, 731012))),
                ('receiver', models.CharField(max_length=64)),
            ],
        ),
    ]
