# Generated by Django 4.0.6 on 2022-07-26 16:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_authrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authrequest',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 16, 30, 22, 583498, tzinfo=utc)),
        ),
    ]
