# Generated by Django 4.0.6 on 2022-07-28 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_authrequest_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='authrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 7, 29, 56, 432117, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='authrequest',
            name='modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authrequest',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 7, 31, 56, 432095, tzinfo=utc)),
        ),
    ]
