# Generated by Django 4.0.6 on 2022-07-28 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_authrequest_created_authrequest_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 12, 35, 57, 518697, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='authrequest',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 12, 37, 57, 518671, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='authrequest',
            name='pass_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
