# Generated by Django 4.0.6 on 2022-07-31 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_pass_code_authrequest_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authrequest',
            old_name='request_method',
            new_name='auth_status',
        ),
        migrations.AlterField(
            model_name='authrequest',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='authrequest',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 11, 1, 26, 400470, tzinfo=utc)),
        ),
    ]
