# Generated by Django 4.0.6 on 2022-08-01 08:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_request_method_authrequest_auth_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authrequest',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='authrequest',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 8, 46, 4, 787804, tzinfo=utc)),
        ),
    ]
