# Generated by Django 4.0.6 on 2022-08-01 08:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_authrequest_code_alter_authrequest_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authrequest',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 8, 46, 48, 664471, tzinfo=utc)),
        ),
    ]
