# Generated by Django 4.0.3 on 2022-05-17 13:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0003_remove_cart_total'),
        ('user', '0003_address_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('p', 'pending'), ('s', 'shipping'), ('c', 'completed')], default='p', max_length=1)),
                ('delivery_date', models.DateField(default=datetime.datetime(2022, 5, 21, 17, 36, 51, 19027))),
                ('order_number', models.CharField(default=order.models.generate_order_number, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='user.address')),
                ('buyer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('cart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
