# Generated by Django 4.0.3 on 2022-05-18 08:13

import datetime
import django.core.validators
from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_address_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2022, 5, 22), validators=[django.core.validators.MinValueValidator(datetime.date(2022, 5, 21))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=order.models.generate_order_number, max_length=10, unique=True),
        ),
    ]
