# Generated by Django 4.0.3 on 2022-05-19 11:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_delivery_date_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 15, 41, 59, 949675)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2022, 5, 23), validators=[django.core.validators.MinValueValidator(datetime.date(2022, 5, 22))]),
        ),
    ]
