# Generated by Django 4.0.5 on 2022-07-14 11:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_created_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2022, 7, 18), validators=[django.core.validators.MinValueValidator(datetime.date(2022, 7, 17))]),
        ),
    ]
