# Generated by Django 4.0.6 on 2022-07-28 07:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_delivery_date_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2022, 8, 1), validators=[django.core.validators.MinValueValidator(datetime.date(2022, 7, 31))]),
        ),
    ]
